export const todoTypes: any = [
  {
    id: 1,
    title: 'Task',
    description: '',
    key: 'task',
    icon: 'task',
  },
  {
    id: 2,
    title: 'Story',
    description: '',
    key: 'story',
    icon: 'auto_stories',
  },
  {
    id: 3,
    title: 'Bug',
    description: '',
    key: 'bug',
    icon: 'bug_report',
  },
  {
    id: 4,
    title: 'Note',
    description: '',
    key: 'note',
    icon: 'sticky_note_2',
  },
  {
    id: 5,
    title: 'Feature',
    description: '',
    key: 'feature',
    icon: 'theaters',
  },
  {
    id: 6,
    title: 'Design',
    description: '',
    key: 'design',
    icon: 'brush',
  },
  {
    id: 7,
    title: 'Logic',
    description: '',
    key: 'logic',
    icon: 'code',
  },
  {
    id: 8,
    title: 'Inspiration',
    description: '',
    key: 'inspiration',
    icon: 'online_prediction',
  },
  {
    id: 9,
    title: 'Idea',
    description: '',
    key: 'idea',
    icon: 'emoji_objects',
  },
  {
    id: 10,
    title: 'To Read',
    description: '',
    key: 'toRead',
    icon: 'menu_book',
  },
  {
    id: 11,
    title: 'To Try',
    description: '',
    key: 'toTry',
    icon: 'shopping_cart',
  },
  {
    id: 12,
    title: 'To Learn',
    description: '',
    key: 'toLearn',
    icon: 'local_library',
  },
  {
    id: 13,
    title: 'How Tos',
    description: '',
    key: 'howTos',
    icon: 'checklist',
  },
];

export const sidebarValues: any = [
  {
    key: 7,
    title: 'Home',
    description: 'Home',
    route: '/',
    icon: 'home',
    children: [],
  },
  {
    key: 6,
    title: 'Overview',
    description: 'All To Dos',
    route: '/overview',
    icon: 'preview',
    children: [],
  },
  {
    key: 1,
    title: 'Inbox',
    description: 'All Items by Date(s)',
    route: '/inbox',
    icon: 'mail',
    children: [],
  },
  {
    key: 2,
    title: 'Tasks',
    description: 'All Tasks and To Dos',
    route: '/tasks',
    icon: 'task',
    children: [],
  },
  {
    key: 3,
    title: 'Notes',
    description: 'Random notes',
    route: '/notes',
    icon: 'sticky_note_2',
    children: [],
  },
  {
    key: 4,
    title: 'Ideas',
    description: 'Ideas and Inspirations',
    route: '/dreams',
    icon: 'lightbulb',
    children: [
      {
        key: 1,
        title: 'Ideas',
        description: 'Ideas',
        route: '/dreams/ideas',
        icon: 'emoji_objects',
        children: [],
      },
      {
        key: 2,
        title: 'Inspirations',
        description: 'Inspirations',
        route: '/dreams/inspirations',
        icon: 'online_prediction',
        children: [],
      },
    ],
  },
  {
    key: 5,
    title: 'Misc',
    description: 'All Other Task Types',
    route: '/others',
    icon: 'apps',
    children: [
      {
        key: 1,
        title: 'To Read',
        description: 'Miscellaneous',
        route: '/others/to-read',
        icon: 'auto_stories',
        children: [],
      },
      {
        key: 2,
        title: 'To Try',
        description: 'Inspirations',
        route: '/others/to-try',
        icon: 'code',
        children: [],
      },
      {
        key: 3,
        title: 'To Learn',
        description: 'Inspirations',
        route: '/others/to-learn',
        icon: 'library_books',
        children: [],
      },
    ],
  },
];

export const todoFormData: { [key: string]: any } = {
  title: {
    key: 'title',
    label: 'Title',
    value: '',
    type: 'text',
    required: true,
    placeholder: 'Enter a title',
  },
  type: {
    key: 'type',
    label: 'Type',
    value: '',
    type: 'select',
    required: true,
    placeholder: 'Select a Type',
    options: todoTypes.map((typ: any) => {
      return { key: typ.key, value: typ.title };
    }),
  },
  assignedTo: {
    key: 'assignedTo',
    label: 'Assigned To',
    value: '',
    type: 'select',
    required: true,
    placeholder: 'Select a User',
  },
  body: {
    key: 'body',
    label: 'Content',
    value: '',
    type: 'textarea',
    rows: 10,
    required: true,
    placeholder: 'Enter the content',
  },
  dueDate: {
    key: 'dueDate',
    label: 'Due Date',
    value: '',
    type: 'date',
    required: true,
    placeholder: new Date(),
  },
  isCompleted: {
    key: 'isCompleted',
    label: 'Mark Complete?',
    value: false,
    type: 'radio',
    required: false,
    options: [
      { title: 'YES', value: true },
      { title: 'NO', value: false },
    ],
  },
  completedDate: {
    key: 'completedDate',
    label: 'Completed Date',
    value: '',
    type: 'date',
    required: true,
    placeholder: new Date(),
  },
};

export const userProfile: any = {
  name: '',
  email: '',
  nickName: '',
  profilePicUrl: '',
  twitter: '',
  facebook: '',
  linkedIn: '',
  instagram: '',
  youtube: '',
  title: '',
  aboutMe: '',
  websiteUrl: '',
};

export const profileFormData: { [key: string]: any } = {
  name: {
    key: 'name',
    label: 'Name',
    value: '',
    type: 'text',
    required: true,
    placeholder: 'Enter your name',
  },
  email: {
    key: 'email',
    label: 'Email',
    value: '',
    type: 'text',
    required: true,
    placeholder: 'Enter your email',
    hide: true,
  },
  nickName: {
    key: 'nickName',
    label: 'Nick Name',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter a shortname for yourself',
  },
  title: {
    key: 'title',
    label: 'Title',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your title',
  },
  profilePicUrl: {
    key: 'profilePicUrl',
    label: 'Profile Pic Image',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'URL will appear here on successful image upload',
    disabled: true,
    hide: true,
  },
  twitter: {
    key: 'twitter',
    label: 'Twitter handle',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your Twitter handle',
  },
  facebook: {
    key: 'facebook',
    label: 'Facebook Profile',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your Facebook profile URL',
  },
  linkedIn: {
    key: 'linkedIn',
    label: 'LinkedIn URL',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your LinkedIn profile URL',
  },
  instagram: {
    key: 'instagram',
    label: 'Instagram URL',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your Instagram URL',
  },
  youtube: {
    key: 'youtube',
    label: 'YouTube URL',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your YouTube URL',
  },
  websiteUrl: {
    key: 'websiteUrl',
    label: 'Website/Blog URL',
    value: '',
    type: 'text',
    required: false,
    placeholder: 'Enter your Website/Blog URL',
  },
  aboutMe: {
    key: 'aboutMe',
    label: 'About Me',
    value: '',
    type: 'textarea',
    required: false,
    placeholder: 'A few words about yourself',
    rows: 4,
  },
};
